version: '3.0'

services:
  #kafka:
  #  image: jeqo/apache-kafka:0.10.1.0-2.11
  #  command: sleep infinity
  #  links:
  #    - zookeeper
  #zookeeper:
  #  image: jeqo/apache-zookeeper:3.4.8
  userinterface:
    image: joac89/ms-userinterface
    build: ./userinterface
    ports:
      - 9001:80
    volumes:
      - .:/code/userinterface
    restart: always
    #network_mode: "none"
  routingdeal:
    image: joac89/ms-routingdeal
    build: ./routingdeal
    ports:
      - 9002:80
    volumes:
      - .:/code/routingdeal
    restart: always
    #network_mode: "host"
  dispatcher:
    image: joac89/ms-dispatcher
    build: ./dispatcher
    ports:
      - 9003:80
    volumes:
      - .:/code/dispatcher
    restart: always
    #network_mode: "host"
  #zookeeper:
  #  image: wurstmeister/zookeeper
  #  ports:
  #    - 2181:2181
  #kafka:
  #  image: ubuntu
  #  build: ./
  #  ports:
  #    - 8080:8080



  #kafka:
  #  image: wurstmeister/kafka
  #  build: ./
  #  ports:
  #    - "9092:9092"
  #  links:
  #    - zookeeper:zk
  #  environment:
  #    KAFKA_ADVERTISED_HOST_NAME: "kafka"
  #    KAFKA_ADVERTISED_PORT: "9092"
  #    KAFKA_ZOOKEEPER_CONNECT: "zk:2181"
      #KAFKA_CREATE_TOPICS: "broker-replicated:1:1, broker-replicated:1:1"




  #  build: ./
  #  environment:
  #    KAFKA_ADVERTISED_HOST_NAME: 172.18.0.1
  #    KAFKA_MESSAGE_MAX_BYTES: 2000000
  #    KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'false'
  #  network_mode: "bridge"
  #mysql:
   #  container_name: flask_mysql
   #  restart: always
   #  image: joac89/ms-mysql
   #  ports:
   #    - "3306:3306"
   #  environment:
   #    MYSQL_ROOT_PASSWORD: '123456'
   #    MYSQL_USER: 'root'
   #    MYSQL_PASS: '123456'
   #  volumes:
   #    - mysql-volume:/var/lib/mysql
 #volumes:
   #mysql-volume